<?php

namespace ContainerQqYqG2o;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTableControllerlivrerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MFinYDt.App\Controller\TableController::livrer()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MFinYDt.App\\Controller\\TableController::livrer()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'livrerRepository' => ['privates', 'App\\Repository\\LivrerRepository', 'getLivrerRepositoryService', true],
        ], [
            'livrerRepository' => 'App\\Repository\\LivrerRepository',
        ]))->withContext('App\\Controller\\TableController::livrer()', $container);
    }
}
