<?php

namespace ContainerQqYqG2o;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTableControllervenderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xz4AyKk.App\Controller\TableController::vender()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xz4AyKk.App\\Controller\\TableController::vender()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'venderRepository' => ['privates', 'App\\Repository\\VenderRepository', 'getVenderRepositoryService', true],
        ], [
            'venderRepository' => 'App\\Repository\\VenderRepository',
        ]))->withContext('App\\Controller\\TableController::vender()', $container);
    }
}
