<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQqYqG2o\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQqYqG2o/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQqYqG2o.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQqYqG2o\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQqYqG2o\App_KernelDevDebugContainer([
    'container.build_hash' => 'QqYqG2o',
    'container.build_id' => 'f5727cbf',
    'container.build_time' => 1734451679,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQqYqG2o');
